name: Github Pages
on:
    push:
        branches:
            - master
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master

            - name: Install && Build
              run: |
                  npm install
                  npm run build
            - name: Deploy Build
              uses: JamesIves/github-pages-deploy-action@releases/v3
              with:
                  ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BRANCH: dist
                  FOLDER: dist
                  CLEAN: true

            - name: OSS
              uses: manyuanrong/setup-ossutil@v2.0
              with:
                  endpoint: "oss-cn-zhangjiakou.aliyuncs.com"
                  access-key-id: ${{secrets.OSS_ACCESSKEY_ID}}
                  access-key-secret: ${{secrets.OSS_ACCESS_KEY_SECRET}}
            - run: ossutil cp -rf dist oss://deepberry/static/omp
